version: '3.7'
services:
  backend:
    image: gcr.io/covid19jf/resource-4-vulnerable-backend
    container_name: backend
    networks:
      - resources-net
    ports:
      - 3001:3001
    env_file:
      - .env.backend
    environment:
      PORT: 3001
  portal:
    image: gcr.io/covid19jf/resource-4-vulnerable-frontend
    container_name: portal
    networks:
      - resources-net
    ports:
      - 3000:3000
    environment:
      PORT: 3000
  admin:
    image: gcr.io/covid19jf/resource-4-vulnerable-frontend
    container_name: admin
    networks:
      - resources-net
    ports:
      - 3000:3000
    environment:
      PORT: 3000

networks:
  resources-net:
