version: '3.7'
services:
  backend:
    image: gcr.io/covid19jf/resource-4-vulnerable-backend
    container_name: backend
    networks:
      - resources-net
    ports:
      - 3001:3001
    env_file:
      - .env.backend
    environment:
      PORT: 3001
  frontend:
    image: gcr.io/covid19jf/resource-4-vulnerable-frontend
    container_name: frontend
    networks:
      - resources-net
    ports:
      - 3000:3000
    environment:
      PORT: 3000
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - resources-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
#      - frontend

networks:
  resources-net:
