name: Test -  Gcloud permissions
on:
  push:
    branches:
      - devops-fixes
      - devops-tests
      - devops

# https://docs.rollbar.com/docs/deploy-tracking

jobs:
  test_permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY_JF_CONTRAFOME }}
          project_id: "jf-contra-fome"
      - run: gcloud components install --quiet beta
      - run: gcloud info
      - run: gcloud beta compute ssh "jf-contra-fome" --zone "us-central1-a" --command="pwd && ls && ls -la /srv/project/"


# test-account-3 + compute-admin + updated metadata with "enable-oslogin"

# test-account-3 -  test-account-3@covid19jf.iam.gserviceaccount.com      iam.serviceAccountUser +  roles/compute.osAdminLogin(compute.instances.get)
#https://github.com/TiagoGouvea/resources4vulnerable/runs/589027832?check_suite_focus=true
#ERROR: (gcloud.beta.compute.ssh) Could not fetch resource:
#         - Required 'compute.instances.get' permission for 'projects/covid19jf/zones/us-central1-a/instances/resources-dev-2'

# test-account-2 -  test-account-2@covid19jf.iam.gserviceaccount.com    iam.serviceAccountUser + iam.serviceAccountAdmin
# https://github.com/TiagoGouvea/resources4vulnerable/runs/588991144?check_suite_focus=true
#ERROR: (gcloud.beta.compute.ssh) Could not fetch resource:
# - Required 'compute.instances.get' permission for 'projects/covid19jf/zones/us-central1-a/instances/resources-dev-2'

# test-account-1 -  test-account-1@covid19jf.iam.gserviceaccount.com  GCP_SA_KEY_TEST_1     instanceadmin + computeadmin
#  Updating project ssh metadata...
#  ........................................................................................................failed.
#  Updating instance ssh metadata...
#  ..........failed.
#ERROR: (gcloud.beta.compute.ssh) Could not add SSH key to instance metadata:
#         - The user does not have access to service account '884116399104-compute@developer.gserviceaccount.com'.  User: '***'.  Ask a project owner to grant you the iam.serviceAccountUser role on the service account

